[package]
name = "fuzzbus"
version = "0.1.0"
authors = ["duslabo <duslabo1@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "1.7.0"
rand = "0.7.3"
argh = "0.1.3"
